// coderoast.ipc.producer.cppm — §8.1 wrapper module (1.5.0). GENERATED by gen_module_wrapper.py,
// hand-verified. Re-exports the package's global-module public surface; defs stay in src/*.cpp
// (.a byte-identical). 1.5.1 will unwrap this into a pure module.
module;
#include "coderoast/ipc/producer/shared_memory_producer.hpp"

export module coderoast.ipc.producer;

export namespace coderoast::ipc::producer
{
using coderoast::ipc::producer::FrameBuilder;
using coderoast::ipc::producer::stable_agent_id;
} // namespace coderoast::ipc::producer
