// coderoast.ipc.core.cppm — §8.1 wrapper module (1.5.0). GENERATED by gen_module_wrapper.py, hand-verified.
// Re-exports the package's global-module public surface; defs stay in src/*.cpp
// (.a byte-identical). 1.5.1 will unwrap this into a pure module.
module;
#include "coderoast/ipc/ipc.hpp"

export module coderoast.ipc.core;

export namespace coderoast::ipc
{
using coderoast::ipc::kSharedChannelMagic;
using coderoast::ipc::kSharedChannelAbiVersion;
using coderoast::ipc::kDefaultSharedChannelSlotCount;
using coderoast::ipc::BackpressurePolicy;
using coderoast::ipc::WaitStrategy;
using coderoast::ipc::ChannelState;
using coderoast::ipc::PushStatus;
using coderoast::ipc::PopStatus;
using coderoast::ipc::ChannelConfig;
using coderoast::ipc::ChannelStats;
using coderoast::ipc::SharedMemorySpscChannel;
using coderoast::ipc::kIpcAbiVersion;
using coderoast::ipc::kDefaultLineFramePayloadBytes;
using coderoast::ipc::FrameFormat;
using coderoast::ipc::LineFrameFlags;
using coderoast::ipc::has_flag;
using coderoast::ipc::is_control_frame;
using coderoast::ipc::LineFrameHeader;
using coderoast::ipc::LineFrame;
using coderoast::ipc::DefaultLineFrame;
}
