// coderoast.ipc.consumer.cppm — §8.1 wrapper module (1.5.0). GENERATED by gen_module_wrapper.py,
// hand-verified. Re-exports the package's global-module public surface; defs stay in src/*.cpp
// (.a byte-identical). 1.5.1 will unwrap this into a pure module.
module;
#include "coderoast/ipc/consumer/causal_reorder_buffer.hpp"
#include "coderoast/ipc/consumer/causal_shm_consumer.hpp"
#include "coderoast/ipc/consumer/consumer_metrics.hpp"
#include "coderoast/ipc/consumer/frame_emitter.hpp"
#include "coderoast/ipc/consumer/ingest.hpp"
#include "coderoast/ipc/consumer/ordered_line_frame_iterator.hpp"
#include "coderoast/ipc/consumer/scoped_shm_channel_set.hpp"
#include "coderoast/ipc/consumer/shared_memory_source.hpp"
#include "coderoast/ipc/consumer/shm_transport_drainer.hpp"
#include "coderoast/ipc/consumer/window_closed_consumer.hpp"

export module coderoast.ipc.consumer;

export namespace coderoast::ipc::consumer
{
using coderoast::ipc::consumer::causal_less;
using coderoast::ipc::consumer::CausalKey;
using coderoast::ipc::consumer::CausalReorderBuffer;
using coderoast::ipc::consumer::CausalShmConsumer;
using coderoast::ipc::consumer::ConsumerEvent;
using coderoast::ipc::consumer::ConsumerEventPayload;
using coderoast::ipc::consumer::ConsumerMetrics;
using coderoast::ipc::consumer::ConsumerObserver;
using coderoast::ipc::consumer::DrainerMetrics;
using coderoast::ipc::consumer::EmitterMetrics;
using coderoast::ipc::consumer::extract_causal_key;
using coderoast::ipc::consumer::FrameEmitter;
using coderoast::ipc::consumer::FrameOrdering;
using coderoast::ipc::consumer::OrderedLineFrameIterator;
using coderoast::ipc::consumer::OrderedLineFrameIteratorConfig;
using coderoast::ipc::consumer::ReorderMetrics;
using coderoast::ipc::consumer::ScopedShmChannelSet;
using coderoast::ipc::consumer::SequenceGapPolicy;
using coderoast::ipc::consumer::SharedMemorySource;
using coderoast::ipc::consumer::ShmTransportDrainer;
using coderoast::ipc::consumer::WindowClosedConsumer;
} // namespace coderoast::ipc::consumer
