name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/**'
      - '.conan2/**'
      - 'CMakeLists.txt'
      - 'CMakeUserPresets.json'
      - 'conanfile.py'
      - 'api/**'
      - 'benchmarks/**'
      - 'tests/**'
      - 'packages.yml'

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CONAN_HOME: ${{ github.workspace }}/.conan2
      CONAN_PROFILE: linux-gcc13-release

    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build python3-pip build-essential

      - name: Setup Conan
        uses: conan-io/setup-conan@v1
        with:
          home: ${{ env.CONAN_HOME }}
          cache_packages: true
          profile_detect: false

      - name: Build and test package
        run: |
          conan create . \
            --profile:host="$CONAN_HOME/profiles/$CONAN_PROFILE" \
            --profile:build="$CONAN_HOME/profiles/$CONAN_PROFILE" \
            --build=missing \
            --build-test=missing