name: Lint

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    uses: CodeRoasted/malf-toolchain/.github/workflows/coderoast-lint.yml@83ad808cb817f26451c18aeb452c33852016b3c5
