name: Lint

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    uses: CodeRoasted/malf-toolchain/.github/workflows/coderoast-lint.yml@925c7188677c7f4347d59ddb67a06224f8e6cafd
