name: Lint

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    uses: CodeRoasted/malf-toolchain/.github/workflows/coderoast-lint.yml@6e6b27c976f7e7ab462f3d4673adde17c5787157
