name: Release

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+']
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag to publish (vMAJOR.MINOR.PATCH)'
        required: true

permissions:
  contents: write
  # Sift needed permissions (PR + actions write)
  pull-requests: write
  actions: write

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    secrets: inherit
  ci:
    needs: lint
    uses: ./.github/workflows/ci.yml
    secrets: inherit
  release:
    needs: ci
    uses: CodeRoasted/malf-toolchain/.github/workflows/coderoast-release.yml@d9aff11ed0cd6fa1609f194c5d6b0369da0b035e
    with:
      tag: ${{ github.event.inputs.tag || github.ref_name }}
      packages: |
        coderoast_ipc_core:core
        coderoast_ipc_consumer:consumer
        coderoast_ipc_producer:producer
      benchmark: 'coderoast_ipc_core_bench=coderoast-ipc-core'
      benchmark-subdir: core
    secrets: inherit
